spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  resources:
    cache:
      period: 1
    chain:
      cache: false
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/vgit_db}
server:
  port: ${SERVER_PORT:8080}
