spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:vgit}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        id:
          new_generator_mappings: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  resources:
    cache:
      period: 1
    chain:
      cache: false
server:
  port: ${SERVER_PORT:8080}
