spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        id:
          new_generator_mappings: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  resources:
    cache:
      period: 1
    chain:
      cache: false
server:
  port: ${SERVER_PORT:8080}
